apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  namespace: converter-demo
  labels:
    app: converter-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: converter-auth
  template:
    metadata:
      labels:
        app: converter-auth
    spec:
      containers:
      - name: converter-auth
        image: gil7788/converter-auth:latest
        ports:
        - containerPort: 8000