apiVersion: v1
kind: Service
metadata:
  name: auth-demo
spec:
  selector:
    app: auth-deployment
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 8000
      nodePort: 30013
  type: NodePort