apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  namespace: converter-demo
  labels:
    app: converter-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: converter-gateway
  template:
    metadata:
      labels:
        app: converter-gateway
    spec:
      containers:
      - name: converter-gateway
        image: gil7788/converter-gateway:latest
        ports:
        - containerPort: 8000
