apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: converter-demo
spec:
  selector:
    app: converter-gateway
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: ClusterIP
